### ISSUE TITLE
Condensed version for codepen use

### ISSUE THREAD

**Issue by artemist** [azazdeaz/react-gsap-enhancer#12]
Hi, 
Nice demos ;) I'm happy to see that cow jumping over the moon get some new life, especially because it's easier to learn from a fork of my own code! So, I'm trying to learn how to use react and gsap together- your tool looks awesome. Forgive me, but I'm a bit of a React n00b, if I want to use this in codepen, do I concatenate all the files in the src folder and remove the import lines? In codepen right now you can use react and select babel and I've had pretty good luck with that, but without something like gulp it's annoying to bring in multiple files.

Thanks!

**Comment by azazdeaz** [comment]
Hi @artemist,

Unfortunately, the cow jumping the moon demo employing a lot of tools that originally designed to be used with a bundler like webpack or browserify. (It meant to be a stress test) I [gave it a try](http://codepen.io/azazdeaz/pen/Bjpprg?editors=001) but it needs some more debugging. I'll come back if i manage to get it work on CodePen.

For start, i advise to use some more straightforward examples like [this](http://codepen.io/azazdeaz/pen/yYavVK?editors=001). And if you want to quickly try out something, the playground demos are also editable.

Also, for simpler use cases you might be good to use GSAP without this tool: https://egghead.io/lessons/react-using-tweenmax-with-react

Thank you for your work on this field, i looking forward to see your new articles and animations!

**Comment by artemist** [comment]
Hi @azazdeaz! Sorry for the delay in response. Thank you for the video, I realize now after working with React a little more that I was overcomplicating things for myself. I appreciate your help and keep up the good work!
