### ISSUE TITLE
Use with ReactTransitionGroup?

### ISSUE THREAD

**Issue by amorino** [azazdeaz/react-gsap-enhancer#13]
Is there any implementation with ReactTransitionGroup similar to [velocity-react](https://github.com/twitter-fabric/velocity-react)?

**Comment by azazdeaz** [comment]
No, not yet, but it could be helpful, thanks for the question!

**Comment by azazdeaz** [comment]
Here is a demo about using react-gsap-enhancer simply with TransitionGroup. 
http://azazdeaz.github.io/react-gsap-enhancer/#/demo/using-transition-group

At this point i don't see the the benefits of having a wrapper component around TransitionGorup but i will be thinking about that. Maybe you can help me with some use cases.
