### ISSUE TITLE
Make stagger-functions available?

### ISSUE THREAD

**Issue by micros123** [azazdeaz/react-gsap-enhancer#14]
I'm wondering if there's a special reason why the staggerTo, staggerFrom, etc functions are not available.  Any chance they will be introduced later?

**Comment by azazdeaz** [comment]
Hi @micros123

You can use every GSAP fetaure in the animation source functions. 
[Here is a demo](http://azazdeaz.github.io/react-gsap-enhancer/#/demo/animate-list-with-stagger) for using ```staggerFrom()```.

**Comment by micros123** [comment]
I'm sorry, you're totally right. Thanks for the demo.
