### ISSUE TITLE
reverse() doesn't work

### ISSUE THREAD

**Issue by vedmant** [azazdeaz/react-gsap-enhancer#16]
Hi, I have this weird problem with reverse() method on controller, I launch it when some particular property was changed, but reverse animation doesn't happen. Tested methods like restart(), time(), they work fine.

**Comment by azazdeaz** [comment]
Hi @vedmant!
I made a quick demo to test this issue but it works for me.
http://codepen.io/azazdeaz/pen/QNdRXy?editors=0010
Can you reproduce it somewhere? (You can fork this pen for example)

**Comment by vedmant** [comment]
It happen when I use componentWillReceiveProps to launch animations when particular properties were changed. I use Redux and control animation states with actions, also this will be complex animation with several components animated responding on particular state change. Reproduced it here http://codepen.io/vedmant/pen/GZrVXO?editors=0110

**Comment by azazdeaz** [comment]
Thanks a lot for your description. It was indeed a bug in react-gsap-enhancer. The fixed version is v0.2.2.

**Comment by vedmant** [comment]
Great, thanks!
