### ISSUE TITLE
Is it possible to use gsap plugins?

### ISSUE THREAD

**Issue by abelovic** [azazdeaz/react-gsap-enhancer#17]
I would like to use the throwPropsPlugin/Draggable. How would I do this?

**Comment by zaklampert** [comment]
+1

**Comment by azazdeaz** [comment]
I have no experience with Draggable, if anyone has an example for this, please share with us :)

**Comment by benstepp** [comment]
We are using Draggable with webpack in our of our projects. Relevant config changes include aliasing off the expected dependencies in webpack.config.js. 

```js
// somewhere in code
require('gsap')
if (typeof window !== 'undefined') require('gsap/src/uncompressed/utils/Draggable')
Draggable.create(/* ... */)

// webpack.config.js
{
  resolve: {
    alias: {
      TweenLite: 'gsap',
      CSSPlugin: 'gsap/src/uncompressed/plugins/CSSPlugin'
  }
}
```
