### ISSUE TITLE
use together with other HOC?

### ISSUE THREAD

**Issue by badtant** [azazdeaz/react-gsap-enhancer#29]
Hi, I'm trying to use GSAP together with another HOC. In this case connect from react-redux. Using es6. However I can't get it to work.

```
import GSAP from 'react-gsap-enhancer';
import { connect } from 'react-redux';

class MyComponent extends React.Component {
  render() {/*...*/}
}

const map = (state) => ({
  countdown: state.countdown
});

export default GSAP(connect(map)(MyComponent));
```

Am I doing this wrong?

**Comment by azazdeaz** [comment]
I'm not sure what are you experiencing but probably changing the HoC order will fix the issue.
like:
```js
export default connect(map)(GSAP(MyComponent))
```

**Comment by badtant** [comment]
That made the connect work, but when trying to add an animation `utils.target` is empty so I cant use the `find` methods.

**Comment by azazdeaz** [comment]
That sounds weird, can you show the code that does this?

**Comment by badtant** [comment]
Set up a codepen with similar code but of course it works there...
http://codepen.io/anon/pen/JRZByV

Gah, can't understand this :)

**Comment by badtant** [comment]
Finaly got it working... Typo from my side.
