### ISSUE TITLE
Pass selector to animation function

### ISSUE THREAD

**Issue by tgienger** [azazdeaz/react-gsap-enhancer#4]
So far I'm liking this plugin, but I would like the ability to pass my selector as an argument, either by object or string, to the animation function. This way I can create one animation function to use on multiple targets. Unless of course there's a way to do this that I haven't discovered :)

**Comment by azazdeaz** [comment]
Hi @tgienger!

Yes, you can pass an object as the second parameter to the ```addAnimation``` and the animation source will get it as options:
```javascript
function animationSource({target, options}) {...}

...
this.addAnimation(animationSource, {foo: this.state.foo})
...
```
I will document this soon, until that, i made a [mini demo on this](http://azazdeaz.github.io/react-gsap-enhancer/#/demo/sending-options-to-the-animation-source)

**Comment by tgienger** [comment]
It makes sense looking at it. I tried it but failed because I wasn't using the es6 parameter destructuring properly. Bad on my part, thanks :)

**Comment by azazdeaz** [comment]
Your welcome! :)
I uploaded [an other demo](http://azazdeaz.github.io/react-gsap-enhancer/#/demo/select-target-with-options) that selecting target according the options and i modified [the previous one](http://azazdeaz.github.io/react-gsap-enhancer/#/demo/sending-options-to-the-animation-source) to use only ES5 and JSX. (There should be more demo using plain ES5 i guess)

Thanks for the issue, i'm closing it then!
