### ISSUE TITLE
redux 'connect' and GSAP

### ISSUE THREAD

**Issue by juanzone** [azazdeaz/react-gsap-enhancer#42]
Hello, 

How can I use react-gsap-enhancer with redux in my react component? 
When i export my class with 'connect' for redux how can I put GSAP?

exemple: 'export default connect(mapStateToProps, mapDispatchToProps)(Component)'

Thanks :)

**Comment by benstepp** [comment]
When using multiple higher order components we use the compose helper from redux where I work.

```jsx
import { compose } from 'redux'

export default compose(
  connect(mapStateToProps, mapDispatchToProps),
  GSAP(),
)(MyComponent)
```

You could also just do the composing manually instead
```jsx
export default connect(mapStateToProps, mapDispatchToProps)(GSAP()(MyComponent))
```

**Comment by juanzone** [comment]
Thanks for the help mate! 
I'll use the compose helper ;)
