### ISSUE TITLE
Cannot decorate component

### ISSUE THREAD

**Issue by ewal** [azazdeaz/react-gsap-enhancer#5]
I get the following error message when trying to decorate a component:

"Warning: React can't find the root component node for data-reactid value `.0.0.0.$=10:0`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time."

What could cause this?

**Comment by azazdeaz** [comment]
Hey, @ewal!

Are you sure you don't have two react copies on your page? The easiest way to check this, is to 
> *open Sources tab in Chrome DevTools. Press Cmd+O (Ctrl+O on Windows) and type “React.js”*

[More about this here](https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375)

**Comment by azazdeaz** [comment]
Finally i know what caused the issue. I had some misunderstanding about migrating packages to react 0.14. With the version 0.1.10 react-gsap-enhancer should work again with react 0.13. Sorry for the braking patch release.

**Comment by ewal** [comment]
And I forgot to answer and test. Thank you :+1:
